extends Node3D
## Smoke test: exercises every shared kit system for a few seconds.
func _ready() -> void:
	var env := WorldEnvironment.new()
	add_child(env)
	var sun := DirectionalLight3D.new()
	add_child(sun)
	PNLook.apply(env, sun)
	var floor_mi := MeshInstance3D.new()
	var pm := PlaneMesh.new(); pm.size = Vector2(60, 60)
	floor_mi.mesh = pm
	floor_mi.material_override = PNLook.terrain_material()
	add_child(floor_mi)
	var sph := MeshInstance3D.new(); sph.mesh = SphereMesh.new(); sph.position = Vector3(0, 1, 0)
	sph.material_override = PNLook.with_outline(PNLook.toon(Color(1, 0.6, 0.2)), 0.03)
	add_child(sph)
	var water := MeshInstance3D.new(); var wm := PlaneMesh.new(); wm.size = Vector2(30, 30); wm.subdivide_width = 40; wm.subdivide_depth = 40
	water.mesh = wm; water.material_override = PNLook.water_material(); water.position = Vector3(0, 0.1, -20)
	add_child(water)
	var coin := MeshInstance3D.new(); var cm := TorusMesh.new(); coin.mesh = cm; coin.material_override = PNLook.glow_material(Color(1, 0.8, 0.2)); coin.position = Vector3(3, 1, 0)
	add_child(coin)
	var grass := MeshInstance3D.new(); var gm := QuadMesh.new(); gm.size = Vector2(0.4, 1.0); gm.center_offset = Vector3(0, 0.5, 0)
	grass.mesh = gm; grass.material_override = PNLook.sway_material(Color(0.2, 0.6, 0.25), Color(0.5, 0.85, 0.35)); grass.position = Vector3(-3, 0, 0)
	add_child(grass)
	var cam := Camera3D.new(); cam.position = Vector3(0, 3, 9); add_child(cam)
	cam.look_at(Vector3(0, 1, 0))
	PNWind.track(sph)
	Juice.dust(Vector3(0, 0.2, 0))
	Juice.sparkle(Vector3(3, 1, 0))
	Juice.popup(Vector3(3, 2, 0), "+1")
	Juice.blob_shadow(sph, 0.7)
	PNAudio.configure_from_look(PNLook.look)
	PNAudio.play_track("smoke")
	PNAudio.pickup(2)
	PNAudio.set_state("danger")
	PNAudio.set_space("cave")
	PNAudio.set_space("open")
	print("PN smoke ok quality=", PNSettings.quality, " look=", PNLook.look.get("id"))
